version: 0.0
os: linux
files:
  - source: docker-compose.production.yml
    destination: /home/ubuntu
  - source: scripts
    destination: /home/ubuntu/scripts  
hooks:
  ApplicationStop:
    - location: ./scripts/before-install.sh
      timeout: 10000
  AfterInstall:
    - location: ./scripts/after-install.sh    
      timeout: 900
  ApplicationStart:
    - location: ./scripts/application-start.sh  
      timeout: 900
  ValidateService:
    - location: ./scripts/validate-service.sh    
      timeout: 900 