version: '3'
services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    restart: always
    networks:
      - mqtt-network
      - app-network
    volumes:
      - ./app:/app/app
    depends_on:
      - postgres
    
      

  postgres:
    image: postgres:latest
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/postgresql/data 
      # To persist the data in the database we have a volume that persist after container deletion
      # and copy the files from the container to the volume.
    

    

  custom_mqtt_container:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    ports:
      - "9001:9001"
    networks:
      - mqtt-network
    restart: always
    command: python mqtt.py
    depends_on:
      - fastapi_app
    volumes:
      - ./mqtt.py:/mqtt/mqtt.py


networks:
  app-network:
    driver: bridge
  mqtt-network:
    driver: bridge

volumes: # All the named volumes needed to persist data after container deletion
  db-volume:
    
