name: export secrets

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: user/app:latest
          secrets: |
            "DB_USER: ${{ secrets.DB_USER }}"
            "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
            "DB_HOST: ${{ secrets.DB_HOST }}"
            "DB_PORT: ${{ secrets.DB_PORT }}"
            "DB_NAME: ${{ secrets.DB_NAME }}"
            "HOST: ${{ secrets.HOST }}"
            "USER: ${{ secrets.USER }}"
            "PASSWORD: ${{ secrets.PASSWORD }}"
            "PORT: ${{ secrets.PORT }}"
            "GROUP_ID: ${{ secrets.GROUP_ID }}"         
